---
title: "Instant HIE v2"
format: html
---


##### Background
Instant OpenHIE (currently Instant OpenHIE v2) aims to allow Health Information Exchange components to be packaged up, deployed, operated and scaled via a simple CLI.


##### MamaToto HIE

All HDC HIE components are packaged as Instant v2 HIE Components.

List of packages:

1. identity-access-manager-keycloak : 
    This component provides an identity and access management (IAM) solution using Keycloak. It authenticates users and authorizes access to the HIE system.
2. reverse-proxy-nginx : 
    This component acts as a reverse proxy, routing incoming traffic to the appropriate backend services within the HIE system based on URL patterns.
3. mamatoto-datastore-hapi-fhir : 
    This component stores and manages health data in a FHIR (Fast Healthcare Interoperability Resources) format. It uses the HAPI FHIR server implementation for data persistence and retrieval.
4. mamatoto-interoperability-layer-openhim : 
    This component acts as an interoperability layer using OpenHIM. It facilitates data exchange between MamaToto HIE and other disparate health information systems.
5. mamatoto-openhim-mediators : 
    These are custom OpenHIM mediators developed specifically for MamaToto HIE. They translate and transform data between different formats to ensure smooth information exchange.


Sample `config.yml` shown below:

```
projectName: MamaToto
image: jembi/platform:latest
logPath: /tmp/logs

packages:
  - reverse-proxy-nginx
  - identity-access-manager-keycloak

customPackages:
  - id: mamatoto-datastore-hapi-fhir
    path: ./mamatoto-datastore-hapi-fhir
  
  - id: mamatoto-interoperability-layer-openhim
    path: ./mamatoto-interoperability-layer-openhim

  - id: mamatoto-openhim-mediators
    path: ./mamatoto-openhim-mediators

profiles:
  - name: mamatoto
    packages:
      - mamatoto-interoperability-layer-openhim
      - reverse-proxy-nginx
      - mamatoto-datastore-hapi-fhir
      - mamatoto-openhim-mediators
      - identity-access-manager-keycloak
    envFiles:
      - .env
    dev: true
    only: true

```

The `config.yml` file is a configuration file used by Instant HIE v2 to define your deployment settings. It specifies various options like the project name, Docker image to use, and which Instant HIE packages to include.

Here's how it's used:

  1. Create the config.yml file: Use a text editor to create a file named config.yml in your project directory.
  2. Edit the configuration options: Paste the content you want into the file, replacing placeholders with your specific values. Refer to the Instant HIE v2 documentation for a detailed explanation of each configuration option.
  3. Use the config.yml file: When using the Instant HIE v2 CLI commands (e.g., instant package up), these commands will reference the config.yml file to determine your deployment configuration.

The provided `config.yml` example demonstrates how to configure an Instant HIE v2 deployment profile for MamaToto HIE. It includes references to the aforementioned components.

By leveraging Instant HIE v2, MamaToto HIE benefits from a simplified deployment process, easier management of its components, and potential scalability for handling increased data exchange needs.