project:
  type: website
  output-dir: _output
  resources: 
    - "assets/"

website:
  title: ""
  navbar:
    logo: logo-pharmaccess.png
    background: white
    logo-alt: "PharmAccess"
    pinned: true
    left:
      - href: index.qmd
        text: Introduction
      - href: docs/getting_started.qmd
        text: Implementation
      - file: docs/phase1/phase1.qmd
        text: Beneficiary Enrollment
      - file: docs/whatsapp.qmd
        text: WhatsApp
      - file: docs/rationale.qmd
        text: Narrative
      - file: docs/iol/index.qmd
        text: IOL
      - file: docs/shr.qmd
        text: SHR
    right:
      - href: https://github.com/PharmAccess/hdc-documentation
        text: GitHub
  
  sidebar: 
    - id: phase1
      title: Phase 1
      style: "floating"
      search: false
      align: left
      contents: 
        - section: "Phase 1"
          href: docs/phase1/phase1.qmd
          contents:
            # - file: docs/phase1/introduction.qmd
            #   text: Introduction
            - file: docs/phase1/workflow.qmd
              text: Workflow
            - file: docs/phase1/technical-components.qmd
              text: Technical Components
            - file: docs/phase1/data-elements.qmd
              text: Data Elements
            - file: docs/phase1/challenges-solutions.qmd
              text: Challenges and Solutions
            - file: docs/phase1/outcomes.qmd
              text: Outcomes
    - id: iol
      title: IOL
      style: "floating"
      search: false
      align: left
      contents: 
        - section: "IOL"
          href: docs/iol/index.qmd
          contents:
            - section: "Challenges"
              contents: 
                - file: docs/iol/challenges/keycloak_intergration.qmd
                - file: docs/iol/challenges/fhir_web.qmd
            - file: docs/iol/iol-customization/iol-customizations.qmd
              text: "IOL Customisation"
            - section: "Instant OpenHIE v2"
              contents: 
                - file: docs/iol/instant-v2/instant_v2.qmd
         

format:
  html:
    theme:
      - litera
      - theme/styles.scss
    grid: 
      gutter-width: 0.8rem
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px
    toc: true
