project:
  type: website
  output-dir: _output
  resources: 
    - "assets/"

execute: 
  freeze: auto

website:
  title: ""
  navbar:
    logo: logo-pharmaccess.png
    background: white
    logo-alt: "PharmAccess"
    pinned: true
    left:
      - href: index.qmd
        text: Index
      - href: docs/background/momcare.qmd
        text: Background
      - file: docs/dak/dak_overview.qmd
        text: Digital Adaptation Kit
      - file: docs/implementation.qmd
        text: Tech Specifications
      - file: docs/software.qmd
        text: Software
    right:
      - href: https://github.com/PharmAccess/hdc-documentation
        text: GitHub
  
  sidebar: 
    - id: dak
      title: Digital Adaptation Kit
      style: "floating"
      search: false
      align: left
      contents: 
        - section: "Digital Adaptation Kit"
          href: docs/dak/dak_overview.qmd
          contents:
            - file: docs/dak/dak_overview.qmd
              text: DAK overview
            - file: docs/dak/dashboard.qmd
              text: Dashboard rules
            #- file: docs/phase1/technical-components.qmd
            #  text: Technical Components
            #- file: docs/phase1/data-elements.qmd
             # text: Data Elements
            #- file: docs/phase1/challenges-solutions.qmd
            #  text: Challenges and Solutions
            #- file: docs/phase1/outcomes.qmd
            #  text: Outcomes
    - id: background
      title: Background
      style: "floating"
      search: false
      align: left
      contents: 
        - section: "Background"
          href: docs/background/momcare.qmd
          contents:
            - section: "Elements"
              contents:
                - file: docs/background/valuepoints.qmd
                  text: ValuePoints
            - section: "Implementations"
              contents:
                - file: docs/background/hanang.qmd
                  text: Hanang
          #contents:
            #- section: "ValuePoints"
              #contents: 
                #- file: docs/iol/challenges/keycloak_intergration.qmd
                #- file: docs/iol/challenges/fhir_web.qmd
           # - file: docs/iol/iol-customization/iol-customizations.qmd
            #  text: "IOL Customisation"
            #- section: "Instant OpenHIE v2"
            #  contents: 
             #   - file: docs/iol/instant-v2/instant_v2.qmd
         

format:
  html:
    theme:
      - litera
      - theme/styles.scss
    grid: 
      gutter-width: 0.8rem
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px
    toc: true
