project:
  type: website
  output-dir: _output
  resources: 
    - "assets/"

execute: 
  freeze: auto

website:
  title: ""
  navbar:
    logo: logo-pharmaccess.png
    background: white
    logo-alt: "PharmAccess"
    pinned: true
    left:
      - href: momcare.qmd
        text: MomCare
      - file: docs/vp/narrative/valuepoints.qmd
        text: ValuePoints
      - file: docs/mamatoto/narrative/rationale.qmd
        text: MamaToto
    right:
      - href: https://github.com/PharmAccess/hdc-documentation
        text: GitHub

  sidebar: 
    - id: valuepoints
      title: ValuePoints
      style: "floating"
      search: false
      align: left
      contents: 
        - section: "Narrative"
          href: docs/vp/narrative/valuepoints.qmd
          contents:
            - file: docs/vp/narrative/valuepoints.qmd
              text: Introduction to ValuePoints
            - file: docs/vp/narrative/abbreviations.qmd
              text: List of Abbreviations
            - file: docs/vp/narrative/financialmodel.qmd
              text: Financial Model
            - file: docs/vp/narrative/hanang.qmd
              text: Implementation in Hanang
        - section: "Digital Adaptation Kit"
          href: docs/vp/dak/dak_overview.qmd
          contents:
            - file: docs/vp/dak/dak_overview.qmd
              text: Objectives of the DAK
            - file: docs/vp/dak/healthinterventions.qmd
              text: Health Interventions
            - file: docs/vp/dak/personas.qmd
              text: Generic Personas
            - file: docs/vp/dak/userscenarios.qmd
              text: User Scenarios
            - file: docs/vp/dak/businessprocesses.qmd
              text: Business Processes
            - file: docs/vp/dak/data-elements.qmd
              text: Core Data Elements
            - file: docs/vp/dak/metrics.qmd
              text: Indicators and Performance Metrics
            - file: docs/vp/dak/requirements.qmd
              text: Functional and non-functional requirements
        - section: "Technical Specification"
          href: docs/vp/techspecs/implementation.qmd
          contents: 
            - file: docs/vp/techspecs/implementation.qmd
              text: General Specifications
            - file: docs/vp/techspecs/pipeline.qmd
              text: Base Tables
            - file: docs/vp/techspecs/metrics.qmd
              text: ValuePoint Dashboards
            - file: docs/vp/techspecs/dhis2.qmd
              text: DHIS2 Reports
        - section: "Software"
          href: docs/vp/software.qmd
          contents: 
            - file: docs/vpsoftware.qmd
              text: Software

format:
  html:
    theme:
      - litera
      - theme/styles.scss
    grid: 
      gutter-width: 0.8rem
      sidebar-width: 300px
      body-width: 1200px
      margin-width: 100px
    toc: false
