project:
  type: website
  output-dir: _output
  resources: 
    - "assets/"

execute: 
  freeze: auto

website:
  title: ""
  navbar:
    logo: logo-pharmaccess.png
    background: white
    logo-alt: "PharmAccess"
    pinned: true
    left:
      - href: momcare.qmd
        text: MomCare
      - file: docs/background/valuepoints.qmd
        text: ValuePoints
      - file: docs/mamatoto/background.qmd
        text: MamaToto
    right:
      - href: https://github.com/PharmAccess/hdc-documentation
        text: GitHub

  sidebar: 
    - id: valuepoints
      title: ValuePoints
      style: "floating"
      search: false
      align: left
      contents: 
        - section: "Narrative"
          href: docs/background/valuepoints.qmd
          contents:
            - file: docs/background/valuepoints.qmd
              text: Introduction to ValuePoints
            - file: docs/background/abbreviations.qmd
              text: List of Abbreviations
            - file: docs/background/financialmodel.qmd
              text: Financial Model
            - file: docs/background/hanang.qmd
              text: Implementation in Hanang
        - section: "Digital Adaptation Kit"
          href: docs/dak/dak_overview.qmd
          contents:
            - file: docs/dak/dak_overview.qmd
              text: Objectives of the DAK
            - file: docs/dak/healthinterventions.qmd
              text: Health Interventions
            - file: docs/dak/personas.qmd
              text: Generic Personas
            - file: docs/dak/userscenarios.qmd
              text: User Scenarios
            - file: docs/dak/businessprocesses.qmd
              text: Business Processes
            - file: docs/dak/data-elements.qmd
              text: Core Data Elements
            - file: docs/dak/metrics.qmd
              text: Indicators and Performance Metrics
            - file: docs/dak/requirements.qmd
              text: Functional and non-functional requirements
        - section: "Technical Specification"
          href: docs/implementation.qmd
          contents: 
            - file: docs/implementation.qmd
              text: Tech Specifications
        - section: "Software"
          href: docs/software.qmd
          contents: 
            - file: docs/software.qmd
              text: Software

format:
  html:
    theme:
      - litera
      - theme/styles.scss
    grid: 
      gutter-width: 0.8rem
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px
    toc: true
