project:
  type: website
  output-dir: _output
  resources: 
    - "assets/"

execute: 
  freeze: auto

website:
  title: "Connected Care"
  navbar:
    logo: logo-pharmaccess.png
    background: white
    logo-alt: "PharmAccess"
    pinned: true
    left:
      - file: docs/momcare/narrative/momcare.qmd
        text: MomCare
      - file: docs/vp/narrative/valuepoints.qmd
        text: ValuePoints Tool
      - file: docs/whatsapp/narrative.qmd
        text: (WhatsApp Engagement)
      - file: docs/hybridcaremodel/narrative.qmd
        text: (Hybrid Care Model)
    right:
      - href: https://github.com/PharmAccess/hdc-documentation
        text: GitHub

  sidebar: 
    - id: valuepoints
      title: ValuePoints
      style: "floating"
      search: false
      align: left
      contents: 
        - section: "Narrative"
          href: docs/vp/narrative/valuepoints.qmd
          contents:
            - file: docs/vp/narrative/valuepoints.qmd
              text: Introduction to ValuePoints
            - file: docs/vp/narrative/abbreviations.qmd
              text: List of Abbreviations
            - file: docs/vp/narrative/journeytracking.qmd
              text: Journey Tracking
            - file: docs/vp/narrative/interoperability.qmd
              text: Interoperability
            - file: docs/vp/narrative/financialmodel.qmd
              text: Financial Model
            - file: docs/vp/narrative/hanang.qmd
              text: Implementation in Hanang
        - section: "Digital Adaptation Kit"
          href: docs/vp/dak/dak_overview.qmd
          contents:
            - file: docs/vp/dak/dak_overview.qmd
              text: 1. Objectives of the DAK
            - file: docs/vp/dak/healthinterventions.qmd
              text: 2. Health Interventions
            - file: docs/vp/dak/personas.qmd
              text: 3. Generic Personas
            - file: docs/vp/dak/userscenarios.qmd
              text: 4. User Scenarios
            - file: docs/vp/dak/businessprocesses.qmd
              text: 5. Business Processes
            - file: docs/vp/dak/data-elements.qmd
              text: 6. Core Data Elements
            - file: docs/vp/dak/metrics.qmd
              text: 7. Indicators and Performance Metrics
            - file: docs/vp/dak/requirements.qmd
              text: 8. Functional and non-functional requirements
        - section: "Analytics Documentation"
          href: docs/vp/analytics/implementation.qmd
          contents:
            - file: docs/vp/analytics/introduction.qmd
              text: 1. Introduction
            - file: docs/vp/analytics/background.qmd
              text: Background & Rationale
            - file: docs/vp/analytics/system.qmd
              text: System Overview & Flow
            - file: docs/vp/analytics/tools.qmd
              text: Tools & Technologies
            - file: docs/vp/analytics/models.qmd
              text: Models
            - file: docs/vp/analytics/appendix.qmd
              text: Additional Materials
            - file: docs/vp/analytics/implementation.qmd
              text: (General Specifications)
            - file: docs/vp/analytics/pipeline.qmd
              text: (Base Tables)
            - section: ValuePoints Calculations
              contents:
                - file: docs/vp/analytics/sqlonfhir.qmd
                  text: (Analytical approaches)
                - file: docs/vp/analytics/valuepoints.ipynb
                  text: (SQL on FHIR Implementation)
            - file: docs/vp/analytics/metrics.qmd
              text: (ValuePoint Dashboards)
            - file: docs/vp/analytics/dhis2.qmd
              text: (DHIS2 Reports)
        # - section: "Software"
        #   href: docs/vp/vpsoftware.qmd
        #   contents: 
        #     - file: docs/vp/vpsoftware.qmd
        #       text: Software
    - id: momcare
      title: MomCare
      style: "floating"
      search: false
      align: left
      contents: 
        - section: "Narrative"
          href: docs/momcare/narrative/momcare.qmd
          contents:
            - file: docs/momcare/narrative/momcare.qmd
              text: The MomCare Model
            - file: docs/momcare/narrative/digitalcare.qmd
              text: Digitally Connected Care
            - file: docs/momcare/narrative/hie.qmd
              text: Health Information Exchange
            - file: docs/momcare/narrative/connectedcare.qmd
              text: Connected Care Components
        - section: "Digital Adaptation Kit"
          href: docs/momcare/dak/dak.qmd
          contents:
            - file: docs/momcare/dak/dak.qmd
              text: MomCare DAK
            - file: docs/momcare/dak/instanthie.qmd
              text: Instant OpenHIE
            - file: docs/momcare/dak/shr.qmd
              text: Shared Health Record
        - section: "Technical Specification"
          href: docs/momcare/analytics/gettingstarted.qmd
          contents: 
            - file: docs/momcare/analytics/gettingstarted.qmd
              text: Getting Started
            - file: docs/momcare/analytics/information.qmd
              text: Further Information 
    - id: whatsapp
      title: WhatsApp Enrolment
      style: "floating"
      search: false
      align: left
      contents: 
        - section: "Narrative"
          href: docs/whatsapp/narrative.qmd
          contents:
            - file: docs/whatsapp/narrative.qmd
              text: WhatsApp Enrolment
        - section: "Digital Adaptation Kit"
          href: docs/whatsapp/dak/objectivesofdak.qmd
          contents:
            - file: docs/whatsapp/dak/objectivesofdak.qmd
              text: 1. Objectives of the DAK
            - file: docs/whatsapp/dak/healthinterventions.qmd
              text: 2. Health Interventions
            - file: docs/whatsapp/dak/personas.qmd
              text: 3. Generic Personas
            - file: docs/whatsapp/dak/userscenarios.qmd
              text: 4. User Scenarios
            - file: docs/whatsapp/dak/businessprocesses.qmd
              text: 5. Business Processes
            - file: docs/whatsapp/dak/dataelements.qmd
              text: 6. Core Data Elements
            - file: docs/whatsapp/dak/metrics.qmd
              text: 7. Indicators and Performance Metrics
            - file: docs/whatsapp/dak/requirements.qmd
              text: 8. Functional and non-functional requirements
    - id: hybridcaremodel
      title: Hybrid Care Model
      style: "floating"
      search: false
      align: left
      contents: 
        - section: "Narrative"
          href: docs/hybridcaremodel/narrative.qmd
          contents:
            - file: docs/hybridcaremodel/narrative.qmd
              text: Background
        - section: "Digital Adaptation Kit"
          href: docs/hybridcaremodel/dak/objectivesofdak.qmd
          contents:
            - file: docs/hybridcaremodel/dak/objectivesofdak.qmd
              text: 1. Objectives of the DAK
            - file: docs/hybridcaremodel/dak/healthinterventions.qmd
              text: 2. Health Interventions
            - file: docs/hybridcaremodel/dak/personas.qmd
              text: 3. Generic Personas
            - file: docs/hybridcaremodel/dak/userscenarios.qmd
              text: 4. User Scenarios
            - file: docs/hybridcaremodel/dak/businessprocesses.qmd
              text: 5. Business Processes
            - file: docs/hybridcaremodel/dak/dataelements.qmd
              text: 6. Core Data Elements
            - file: docs/hybridcaremodel/dak/metrics.qmd
              text: 7. Indicators and Performance Metrics
            - file: docs/hybridcaremodel/dak/requirements.qmd
              text: 8. Functional and non-functional requirements

format:
  html:
    theme:
      - litera
      - theme/styles.scss
    grid: 
      gutter-width: 0.8rem
      sidebar-width: 300px
      body-width: 1200px
      margin-width: 100px
    toc: false