---
title: "MomCare"
format: html
---

##### MomCare: PharmAccess Maternal & Child Health Program

MomCare is a digital pregnancy care bundle built on the following three pillars:  value-based financing, patient-centered (digital) care delivery and quality improvement tools. It is a set of interventions that together improve health outcomes, enabled by mobile technology and data exchange. To date, MomCare has supported over 60,000 women in Kenya and Tanzania in more than 70 clinics, resulting in good-quality pregnancy journeys at predictable cost. 

The table below provides an overview of all the interventions in the MomCare bundle for reference. This guideline covers specifics needed to implement the ValuePoints. Additional guidelines will be made available for other interventions over time to support complete implementation of the MomCare principles. 

| **MomCare Element**                | **Software Component**                                                  | **MomCare Implementation**                                                                                                                               |
|-----------------------------------|-------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------|
| **Digitally Connected Care Journey** | *Health Data Exchange Architecture*  <br> _(Interoperability Layer & Business Service)_ | [🔗 Connected Care](/docs/mamatoto/index.qmd)                                                                                   |
| **Direct Patient Engagement Channel** | *Point of Service System*                                               | [💬 WhatsApp](docs/whatsapp/narrative.html)                                                                                                              |
| **Journey-Based Analytics Dashboard** | *Analytics Service*                                                     | [📊 ValuePoints Tool](https://pharmaccess.github.io/momcare-valuepoints-documentation/docs/vp/narrative/valuepoints.html)                                |
| **Continuous Care Services**         | *Integrated Point of Service Systems*                                   | [🩺 Hybrid Care Model](https://pharmaccess.github.io/momcare-valuepoints-documentation/docs/hybridcaremodel/narrative.html)                              |
