# Objectives of the DAK

#### Objectives
This DAK focusses on the implementation of the intervention “ValuePoints – Smart incentives to improve pregnancy journeys”, which includes a digital component in the form of a facility performance metrics dashboard. The objective of this DAK is to guide program managers and end-user of the dashboard on how to implement, interpret, and act on the dashboard.

**Important note**: This dashboard is based on patient data that is collected during the (expecting) mother’s pregnancy journey. <u>It is not</u> the objective of this DAK to guide the end-user on how to perform such ANC procedures, nor is it to guide on the process of obtaining data elements in digital systems. Those processes have been described in detail in other WHO guidelines:

-	[WHO recommendations on antenatal care for a positive pregnancy experience.](https://www.who.int/publications/i/item/9789241549912)
-	[Digital Adaptation Kit for Antenatal Care: Operational Requirements for Implementing WHO Recommendations in Digital Systems.](https://www.aidsdatahub.org/sites/default/files/resource/who-digital-adaptation-kit-antenatal-care-2021.pdf) 

For user readability and understanding of how this intervention fits within the common MNCH care practices, some of these practices have been taken along in this DAK in a simplified form.

#### Assumptions
For implementation of the intervention described in this DAK, it is assumed that:

- A healthcare facility records the basic data elements listed in section “Core data elements” in a digital healthcare system (regardless of the processes or systems used to collect such data). Advised is to follow the guidelines mentioned above.
- [OTHER ASSUMPTIONS?]