version: '3.8'

services:
  docs:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    command: quarto preview --host 0.0.0.0 --port 4040
    networks:
      - cloudbuild
    ports:
      - "4040:4040"
    environment:
      - QUARTO_PORT=4040



networks:
  cloudbuild:
    external: true