---
title: "Hanang"
format: html
---
#### Implementation in Hanang

### Pregnancy Journey Quality Indicators
Value Points are assigned to key service indicators across the pregnancy journey. These indicators are defined as:
Early ANC: An antenatal care (ANC) visit registered within the first 12 weeks of pregnancy (ANC < 12 weeks)
ANC profile: Full antenatal care profile administered.

To count the mothers who had a full ANC profile, we check for visits that include the following procedures:
•	VDRL test 
•	hemoglobin
•	blood grouping
•	HIV test
•	blood pressure
•	urine test
In addition, the ANC profile should take place during the first visit.

Ultrasound before end of second trimester: We check for visits with an ultrasound procedure that occurred within the first 24 weeks of pregnancy. (Ultrasound < 24 weeks)
4+ ANCs: Four or more registered antenatal care visits. Clinics receive 0.5 points per visit for the first 4 visits. For further ANC visits no more points are received.
Facility Based Birth: We filter mothers that have given birth at a healthcare facility.
2+ PNCs: Two or more registed postnatal care (PNC) visits. Clinics receive 0.5 points per visit for the first 2 visits. For further PNC visits no more points can be obtained.

### Provider Dashboards
The service indicators could be monitored in the ValuePoints dashboard, available to the individual care provider and the district managers. The VP system automatically generates these VP dashboards from patient data, allowing providers to visualize the completeness of maternal care and act promptly to deliver better value. The dashboard displayed ValuePoints as obtained points compared to the total missed and attainable points for the specific providers. Additionally, the providers’ VPs were compared to the average percentage of points earned at other providers. This way insights about care delivery were generated for health management both at the provider and district level.
Dashboard screenshots
The dashboards present a summarized view of the ValuePoints across their patient population. This dashboard includes a few elements:
1.	Patients per trimester: This element shows how the pregnancy journeys of active maternal care users are distributed for this specific clinic.
2.	Total ValuePoints: This indicates the percentage of the obtained ValuePoints out of the attainable ValuePoints. It provides the sum of ValuePoints and the total budget this translates into in the provider wallet.
3.	Monthly Performance
4.	Service Specific Perfomance
5.	Journey performance over Time
6.	Indicators over Time
The dashboard allowed stratification by risk groups to enable closer monitoring and promote risk prevention measures. High risk patients were defined based on existing health complications, or high age. Teenagers were defined as (under 18 years old).
•	Definition of risk groups

### Financial model
Each indicator was assigned a Value Point that can be attained by the provider and linked to a monetary reward of 7,500 TSh. Value Points can also obtained in a shared manner; for example when one facility referred to another for ultrasound, the VP for this service would be shared across the two. Adequate reporting of services in the ValuePoint system by the provider thereby generated extra budget to procure additional resources for care delivery.
The sum of the rewards linked to the obtained ValuePoints, was calculated in the provider’s wallet.
In the Hanang implementation, the available budget in the wallet was used to place orders for necessary supplies, such as equipment, medication. The local PharmAccess team managed the procurement and delivery of supplies based on providers choices. As such the VP system assumed that these incentives would drive improved agency and (collaborative) resource management, ultimately impacting the quality and value of care delivery.
