# Core data elements
This section outlines the minimum set of data needed to enroll the pregnant woman into the Hybrid care model and the information shared between then providers.

[THIS SECTION REQUIRES A REVIEW ON THE DATA ELEMTNS FROM CHRIS]

###### Core data elements - Enrolment in hybrid care model
###### Core data elements – One time collection at registration
<table style="border-collapse: collapse; width: 100%;">
  <thead style="background-color: #ADD8E6;">
    <tr>
      <th style="padding: 12px; text-align: left; border-bottom: 1px solid #ccc;">Activity ID and name</th>
      <th style="padding: 12px; text-align: left; border-bottom: 1px solid #ccc;">Data element ID</th>
      <th style="padding: 12px; text-align: left; border-bottom: 1px solid #ccc;">Data element name</th>
      <th style="padding: 12px; text-align: left; border-bottom: 1px solid #ccc;">Description and definition</th>
    </tr>
  </thead>
  <tbody>
    <tr style="border-bottom: 1px solid #ccc;">
      <td style="padding: 12px;">MMT.B.create or update beneficiary to a policy</td>
      <td style="padding: 12px;">MMT.B.DE1</td>
      <td style="padding: 12px;">Beneficiary identification</td>
      <td style="padding: 12px;">The identity of the beneficiary.</td>
    </tr>
    <tr style="border-bottom: 1px solid #ccc;">
      <td style="padding: 12px;"></td>
      <td style="padding: 12px;">MMT.B.DE2</td>
      <td style="padding: 12px;">Identification type</td>
      <td style="padding: 12px;">The type of identification document.</td>
    </tr>
    <tr style="border-bottom: 1px solid #ccc;">
      <td style="padding: 12px;"></td>
      <td style="padding: 12px;">MMT.B.DE3</td>
      <td style="padding: 12px;">Identification number</td>
      <td style="padding: 12px;">The identification number of the given identification document.</td>
    </tr>
    <tr style="border-bottom: 1px solid #ccc;">
      <td style="padding: 12px;"></td>
      <td style="padding: 12px;">MMT.B.DE4</td>
      <td style="padding: 12px;">Accept Terms And Conditions</td>
      <td style="padding: 12px;">Terms and Conditions.</td>
    </tr>
    <tr style="border-bottom: 1px solid #ccc;">
      <td style="padding: 12px;"></td>
      <td style="padding: 12px;">MMT.B.DE5</td>
      <td style="padding: 12px;">Beneficiary Type</td>
      <td style="padding: 12px;">The type of beneficiary they are.</td>
    </tr>
    <tr style="border-bottom: 1px solid #ccc;">
      <td style="padding: 12px;"></td>
      <td style="padding: 12px;">MMT.B.DE6</td>
      <td style="padding: 12px;">Occupation</td>
      <td style="padding: 12px;">The occupation of the beneficiary.</td>
    </tr>
    <tr style="border-bottom: 1px solid #ccc;">
      <td style="padding: 12px;"></td>
      <td style="padding: 12px;">MMT.B.DE7</td>
      <td style="padding: 12px;">Employee Code</td>
      <td style="padding: 12px;">The employee code of the beneficiary.</td>
    </tr>
    <tr style="border-bottom: 1px solid #ccc;">
      <td style="padding: 12px;"></td>
      <td style="padding: 12px;">MMT.B.DE8</td>
      <td style="padding: 12px;">Work Country Code</td>
      <td style="padding: 12px;">Code that represents the beneficiary's country workplace.</td>
    </tr>
    <tr style="border-bottom: 1px solid #ccc;">
      <td style="padding: 12px;"></td>
      <td style="padding: 12px;">MMT.B.DE9</td>
      <td style="padding: 12px;">Work County Code</td>
      <td style="padding: 12px;">Code that represents the beneficiary's county workplace.</td>
    </tr>
    <tr style="border-bottom: 1px solid #ccc;">
      <td style="padding: 12px;"></td>
      <td style="padding: 12px;">MMT.B.DE10</td>
      <td style="padding: 12px;">Work Location Code</td>
      <td style="padding: 12px;">Code that represents the beneficiary's location at the workplace.</td>
    </tr>
    <tr style="border-bottom: 1px solid #ccc;">
      <td style="padding: 12px;"></td>
      <td style="padding: 12px;">MMT.B.DE11</td>
      <td style="padding: 12px;">Department</td>
      <td style="padding: 12px;">Beneficiary’s department at the place of work.</td>
    </tr>
    <tr style="border-bottom: 1px solid #ccc;">
      <td style="padding: 12px;"></td>
      <td style="padding: 12px;">MMT.B.DE12</td>
      <td style="padding: 12px;">Profession</td>
      <td style="padding: 12px;">Beneficiary’s profession.</td>
    </tr>
    <tr style="border-bottom: 1px solid #ccc;">
      <td style="padding: 12px;"></td>
      <td style="padding: 12px;">MMT.B.DE13</td>
      <td style="padding: 12px;">Salary</td>
      <td style="padding: 12px;">Beneficiary’s current salary.</td>
    </tr>
    <tr style="border-bottom: 1px solid #ccc;">
      <td style="padding: 12px;"></td>
      <td style="padding: 12px;">MMT.B.DE14</td>
      <td style="padding: 12px;">Commission</td>
      <td style="padding: 12px;">Beneficiary’s commission.</td>
    </tr>
  </tbody>
</table>

<br>


###### Core data elements - Patient information stored in the Shared Health Record


